name: Spring Boot Docker CI-CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  spring-ci:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.new_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Version
        id: version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          echo "âœ… Generated version: $VERSION"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Set Gradle permissions
        run: chmod +x gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew clean build --no-daemon

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login \
            --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Express Image
        run: |
          VERSION=${{ steps.version.outputs.new_version }}
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-17/be
          
          docker build -t $REPO:$VERSION .
          docker push $REPO:$VERSION
          
          echo "âœ… Successfully pushed: $REPO:$VERSION"

  spring-cd:
    needs: spring-ci
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via Docker Compose
        run: |
          VERSION="${{ needs.spring-ci.outputs.version }}"

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_HOST }} << EOF

            aws ecr get-login-password --region ap-northeast-2 | \
              sudo docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
              
              cd /home/${{ secrets.SERVER_USER }}
          
              echo "ðŸ“¦ Pulling image: be:$VERSION"

              sudo BACKEND_VERSION=$VERSION docker compose pull
              sudo BACKEND_VERSION=$VERSION docker compose up -d --remove-orphans
            
              echo "âœ… Deployment completed: version $VERSION" 
          EOF